apiVersion: skaffold/v4beta7
kind: Config
build:
  artifacts:
    - image: chaintrap-maptool
      context: .
  local:
    push: true
    useBuildkit: true
    concurrency: 8

deploy:
  helm:
    releases:
      - name: chaintrap-{{.USER}}
        chartPath: helm/chaintrap
        createNamespace: true
        # skipBuildDependencies: true # should be true when using remote helm dependencies
        valuesFiles:
          - "helm/chaintrap/project-values.yaml"
          - "helm/chaintrap/subsystem-values.yaml"
          - "../ops/hoy-charts/values/platforms/hoy/values.yaml"
        setValueTemplates:
          maptool.image: "{{.IMAGE_FULLY_QUALIFIED_chaintrap_maptool}}"
          platform.imageConfig.registry: "{{.IMAGE_DOMAIN_chaintrap_maptool}}"
          platform.imageConfig.repository: "{{.IMAGE_REPO_NO_DOMAIN_chaintrap_maptool}}"
        setValues:
          platform.imageConfig.pullPolicy.default: Always
