# This Deployment manifest defines:
# - single-replica deployment of the container image, with label "app: go-hello-world"
# - Pod exposes port 8080
# - specify PORT environment variable to the container process
# Syntax reference https://kubernetes.io/docs/concepts/configuration/overview/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maptool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maptool
  template:
    metadata:
      labels:
        app: maptool
    spec:

      containers:
        - name: service
          image: maptool
          ports:
            - name: app-port
              containerPort: 8000

          env:
            - name: MAPTOOL_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: maptool
                  key: MAPTOOL_ADDRESS

            - name: MAPTOOL_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: maptool
                  key: MAPTOOL_PREFIX

          startupProbe:
            httpGet:
              path: /healthz
              port: app-port
            failureThreshold: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /healthz
              port: app-port
            initialDelaySeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: app-port
            failureThreshold: 1
            periodSeconds: 30
