project:
  name: chaintrap
  default:
    serviceType: ClusterIP
    # Using Recreate as the default would be a dev focused and light weight, but will
    # cause down time.
    rolloutStrategy: Recreate
    # rolloutStrategy: RollingUpdate
    #rollingUpdate:
    #  # Note: I expect the absoloute of 1 to work even for deployments with a
    #  # single instance
    #  maxUnavailable: 1

